### ISSUE TITLE
Testing the Smart Contract

### ISSUE THREAD

**Issue by supriya-045** [opencodeiiita/Auction-DApp#11]
Write the code for testing the smart contract in javascript or solidity named as `bidder.js or bidder. sol` under the test/ directory.
It is pretty advanced, and you should include all the functionality as the bidder smart contracts wanted to, like if the bidding amount is appropriate, it will pass it for a transaction or display it, otherwise reject it directly.

**Comment by schandu-eng** [comment]
Claim

**Comment by codelord09** [comment]
Claim

**Comment by Puja-Saraf** [comment]
claim

**Comment by supriya-045** [comment]
> since two days are over, can I claim this? @supriya-045

Please wait till 6 pm.
