### ISSUE TITLE
Write the function for setting up bidder data.

### ISSUE THREAD

**Issue by supriya-045** [opencodeiiita/Auction-DApp#22]
This should be done after #21 .
Basically you need to write function for setting up the bidder data.

**Comment by medhatiwari** [comment]
claim

**Comment by medhatiwari** [comment]
@supriya-045 from pr #23 `contract_linking.dart`
in getBidderData() variables : _`displayEligibility` , `bidderName`, `bidAmount` were not declared previously in the contract_linking.dart.
Should I also declare them? as I need to call getBidderData() in setBidderData()
