### ISSUE TITLE
Write the smart contract for bidding.

### ISSUE THREAD

**Issue by supriya-045** [opencodeiiita/Auction-DApp#3]
It should contains code for  biddername  , bidding amount, also define a minimum bidding amount and contain a function which approve the proposal for bidding.

**Comment by medhatiwari** [comment]
Hey I want to work on this. Assign this issue to me

**Comment by NEHA15012002** [comment]
claim

**Comment by schandu-eng** [comment]
I want to work on this issue please assign it to me

**Comment by Abhijeet452** [comment]
Claim

**Comment by supriya-045** [comment]
Thanks for your interest here.  I will assign this issue if it is not completed by the assigned participant then  I will again open issue for all then claim again. :)

**Comment by vaibhavsahu342** [comment]
Hey I want to work on this. Assign this issue to me
