### ISSUE TITLE
Write deploying file in javascript

### ISSUE THREAD

**Issue by supriya-045** [opencodeiiita/Auction-DApp#5]
You’ll see one JavaScript file already in the migrations/ directory: `1_initial_migration.js. `This handles deploying the Migrations.sol contract to observe subsequent smart contract migrations, and ensures we don’t double-migrate unchanged contracts in the future.

Now you have to create h new file named `2_deploy_contracts.js` like that  in the migrations/ directory for migrations of contracts.

**Comment by jalanprakhar** [comment]
claim

**Comment by isharawat** [comment]
claim

**Comment by supriya-045** [comment]
> claim

Go ahead...

**Comment by vaibhavsahu342** [comment]
claim

**Comment by vaibhavsahu342** [comment]
claim
